package main

import (
	"fmt"
)

func main() {
	fmt.Printf(`
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello brave new autogenerated world!");
	fmt.Println("This is live!");
}
	`)
}
